preview = true
unsafe-fixes = true
fix = true
target-version = "py312"


[format]
preview = true
line-ending = "lf"
docstring-code-format = true


[lint]
preview = true

# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    ### recommended rules to disable to avoid formatter conflicts
    "W191",     # tab indentation
    "E111",     # indentation not a valid multiple of indent-width
    "E114",     # comment indentation not a valid multiple of indent-width
    "E117",     # comment over-indented
    "D206",     # docstring indented with tabs
    "D300",     # triple single-quotes
    "Q000",     # inline strings single-quoted
    "Q001",     # multi-line string single-quoted
    "Q002",     # docstring single-quoted
    "Q003",     # avoidable escapes due to quote style
    "COM812",   # missing trailing comma
    "COM819",   # prohibited trailing comma
    "ISC001",   # implicitly-concatenated string literal on one line
    "ISC002",   # implicitly-concatenated string literal over multiple lines
    ###

    "FBT",      # 'boolean traps' (bools as function args)
    "CPY",      # missing copyright notice at start of file
    "T20",      # `print` statements
    "D105",     # missing docstring in magic method
    "D107",     # missing docstring in `__init__`
    "D213",     # multi-line docstring summary starts at second line
                #     (ignored in favor of D212, summary at first line)
    "S311",     # use of `random`
    "PLR0913",  # too many function args (lint.pylint.max-args, default 5)
    "PLR0917",  # too many positional function args
                #     (lint.pylint.max-positional-args, default 5)
]
unfixable = [
    "F401",     # unused import
    "F541",     # f-string without placeholders
    "F601",     # dictionary key literal name repeated
    "F602",     # dictionary key name repeated
    "F841",     # unused variable
    "D200",     # overlong one-line docstring
    "D212",     # multi-line docstring summary doesn't start at first line
]


[lint.flake8-annotations]
mypy-init-return = true  # allow omitting return type for __init__()
